### ISSUE TITLE
Plugin will stop updating domoticz if Airly sensor is not reachable

### ISSUE THREAD

**Issue by mstojek** [lrybak/domoticz-airly#1]
If Airly sensor connection fails plugin will never update Domoticz since we set variable self.inProgress = True and never change it to False.

Proposed fix in function OnHeartbeat around line 360:
        except SensorNotFoundException as snfe:
            self.inProgress = False
            Domoticz.Error(_("Sensor id (%(sensor_id)d) not exists") % {'sensor_id': int(Parameters["Mode2"])})
        except UnauthorizedException as ue:
            self.inProgress = False
            Domoticz.Error(_("Not authorized"))

As you can see I added "self.inProgress = False" when exception is caught.

**Comment by lrybak** [comment]
Hello,
Thanks for reporting the issue. It's fixed already in v0.2. 
self.inProgress is set to False in the 'finally' block
