### ISSUE TITLE
Pobieranie danych ze: Stacja Państwowego Monitoringu Powietrza

### ISSUE THREAD

**Issue by jurekos** [lrybak/domoticz-airly#10]
Cześć,
na początek - świetna wtyczka - nie maiłem problemów z dodaniem i obsługą.
Mam natomiast pytanie odnośnie pobierania danych z innych czujników niż Airly : Stacje Państwowego Monitoringu Powietrza. Chodzi o NOx i SOx i O3. Jest szansa że takie stacje tez byłyby obsłużone?
Mam jeszcze mały problem z którym nie mogę sobie poradzić, może to tez nie jest dobre miejsce na takie pytania: jak pobrać dane z procentowych wskaźników przekroczenia normy? Próbowałem 'domoticz.devices('Airly - PM10 Norma').PM10_PERCENTAGE' ale bez rezultatu. Chciałem użyć w powiadomieniach, resztę danych udąło mi się odczytać.
z góry dzięki za odpowiedź.

**Comment by CHKDSK88** [comment]
@jurekos 

Spróbuj czy #11 działa jak trzeba u Ciebie.

**Comment by jurekos** [comment]
> @jurekos
> 
> Spróbuj czy #11 działa jak trzeba u Ciebie.

Jest ok, dziękuję bardzo!
