### ISSUE TITLE
Problem z eksportem danych domoticz => Influxdb

### ISSUE THREAD

**Issue by naurubwiema** [lrybak/domoticz-airly#13]
Witam,
mam problem z eksportem danych z witrualnych sensorów do bazy influx. Zgłaszałem to na forum domoticza, podobne objawy są u innych uzytkowników.
Dane z sensorów temperatury i ciśnienia eksportują się prawidłowo. Niestety dane dotyczące jakości powietrza już nie.
Wątek omówiony jest tutaj: https://www.domoticz.com/forum/viewtopic.php?f=6&t=35830&p=279581&hilit=airly#p279581
Czy da się to jakoś sprawdzić/poprawić?

**Comment by lrybak** [comment]
Problem według mnie jest w Domoticzu który w InfluxDB Datapush dla CustomSensora próbuje wybrać wartość procentową której ten sensor nie reprezentuje. 
![image](https://user-images.githubusercontent.com/5631648/134124096-0a98e8ee-af44-4fd0-952d-d2e0f8239c5e.png)
