### ISSUE TITLE
zaokrąglanie wartosci procentowych dla poprawnego exportu do influxdb

### ISSUE THREAD

**Issue by pkilar43** [lrybak/domoticz-airly#14]
Przy uzyciu data push'a do influxdb wartosc procentowe UNIT_{PM10,PM25}_PERCENTAGE oraz UNIT_AIR_QUALITY_INDEX muszą być liczbami całkowitymi, influxdb dla percentage potrzebuje integera. Prosba o zmiane:

~/domoticz/plugins/domoticz-airly-v2 $ head -n 436 plugin.py |tail -1
                self.variables[self.UNIT_PM10_PERCENTAGE]['sValue'] = str(round((values["PM10"]/self.UNIT_PM10_NORM) * 100))
~/domoticz/plugins/domoticz-airly-v2 $ head -n 442 plugin.py |tail -1
                self.variables[self.UNIT_PM25_PERCENTAGE]['sValue'] = str(round((values["PM25"] / self.UNIT_PM25_NORM) * 100))
~/domoticz/plugins/domoticz-airly-v2 $ head -n 452 plugin.py |tail -1
                self.variables[self.UNIT_AIR_QUALITY_INDEX]['sValue'] = str(round(res["indexes"][0]["value"]))

**Comment by lrybak** [comment]
Nie mam nawet jak tego przetestować bo nie używam już Domoticza. Przygotuj zmianę to zmerguje kod

**Comment by pkilar43** [comment]
Wrzucilem pull requesta.
