### ISSUE TITLE
Błąd (Airly) Nierozpoznany błąd: type NoneType doesn't define __round__ method

### ISSUE THREAD

**Issue by elpaul** [lrybak/domoticz-airly#7]
Hej.
Otrzymuję w logach taki oto błąd: (Airly) Nierozpoznany błąd: type NoneType doesn't define __round__ method
i dane się nie aktualizują.
Czym to może  być spowodowane? 
EDIT:
dzieję się to tylko na jednym czujniku (najbliżej mojej lokalizacji) 7938. Na stronie i w aplikacji airly jest online i pokazuje dane.
Na innych w dalszej okolicy np.: 7817 jest OK

**Comment by lrybak** [comment]
Hej, Sorry za pozna reakcję. 

Chodzi tylko o tą stację 7938? Czy problem nadal występuje?

**Comment by z1mEk** [comment]
Sprawdziłem na tym ID stacji i na najnowszej wersji działa. Zamykam, jeśli błąd się powtórzy otworzymy i będziemy naprawiać.
